// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD1CsBfrctQtGBqqWW0sA1Cjpw3j20YBjw',
    appId: '1:186483186467:web:ecda2836107169c58c8a96',
    messagingSenderId: '186483186467',
    projectId: 'electrino-58e50vr',
    authDomain: 'electrino-58e50vr.firebaseapp.com',
    databaseURL: 'https://electrino-58e50vr-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'electrino-58e50vr.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCrmUw9qYsOAXbYia_k7UOtKMa2aKT99IE',
    appId: '1:1054755416461:android:465c826c79f35359db75c4',
    messagingSenderId: '1054755416461',
    projectId: 'tanglevr',
    databaseURL: 'https://tanglevr-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'tanglevr.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAIQzqc3tIko7mUM4aBJuif2rZvIYC_Rj4',
    appId: '1:1054755416461:ios:af2b09d6680258dedb75c4',
    messagingSenderId: '1054755416461',
    projectId: 'tanglevr',
    databaseURL: 'https://tanglevr-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'tanglevr.appspot.com',
    androidClientId: '1054755416461-9o1eaunj1gq4q6qte047775hslkdsdeh.apps.googleusercontent.com',
    iosClientId: '1054755416461-edca94ql9pfn0dgbpokue5a5at4ufjkn.apps.googleusercontent.com',
    iosBundleId: 'com.example.rentManager',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCHcIvjvspyx8KNSQ5YAHn6pDPNCkZNfGY',
    appId: '1:186483186467:ios:2d9bbdf76aa5b8228c8a96',
    messagingSenderId: '186483186467',
    projectId: 'electrino-58e50vr',
    databaseURL: 'https://electrino-58e50vr-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'electrino-58e50vr.firebasestorage.app',
    androidClientId: '186483186467-og7sg5vct81lab49uplb8quk8fhvqu4f.apps.googleusercontent.com',
    iosClientId: '186483186467-imsuh1ma63pia0qubo1v26481voql041.apps.googleusercontent.com',
    iosBundleId: 'com.example.rentManager',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAIt2SgPV4GhldGbcnjJIPg_NeJnCfQyYo',
    appId: '1:186483186467:web:c10b24ed010ffb258c8a96',
    messagingSenderId: '186483186467',
    projectId: 'electrino-58e50vr',
    authDomain: 'electrino-58e50vr.firebaseapp.com',
    databaseURL: 'https://electrino-58e50vr-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'electrino-58e50vr.firebasestorage.app',
  );

}